name = "strata-quest"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "strata-quest-db"
database_id = "51b900b6-67fd-4881-888f-69e8fa535f7c"
migrations_dir = "drizzle"
